server:
  port: ${PORT:8080}
  servlet:
    context-path: /
  compression:
    enabled: true
  error:
    include-stacktrace: always

spring:
  application:
    name: splitso-service
  security:
    jwt:
      secret: ${JWT_SECRET:dev-secret-key}
      expiration: 86400000
  datasource:
    url: ${DATABASE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false

logging:
  level:
    root: INFO
    com.chsrvn.splitsoservice: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
