spring:
  application:
    name: splitso-service
  security:
    jwt:
      secret: ${JWT_SECRET}
      expiration: 86400000
  mongodb:
    uri: ${DATABASE_URI}

logging:
  level:
    root: info
    com.chsrvn.splitsoservice: debug
  logback:
    rollingpolicy:
      max-history: 10
      max-size: 10MB
